version: '2.4'

services:
  runner:
    entrypoint: "/usr/local/bin/docker-php-xdebug-entrypoint"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.php-cli
      target: dev
    environment:
      SSH_AUTH_SOCK: "${SSH_AUTH_SOCK}"
      XDEBUG_ENABLED: "${XDEBUG_ENABLED:-}"
      XDEBUG_HOST: "${XDEBUG_HOST:-}"
      XDEBUG_PORT: "${XDEBUG_PORT:-}"
      XDEBUG_IDE_KEY: "${XDEBUG_IDE_KEY:-}"
      PHP_IDE_CONFIG: "${PHP_IDE_CONFIG:-}"
    volumes:
      - "..:/app:rw"
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}:ro"
