# syntax=docker/dockerfile:1.0.0-experimental
FROM lendableuk/php-fpm-alpine:7.4.9-alpine3.11 as base

COPY --from=composer:2.1.3 /usr/bin/composer /usr/bin/composer

RUN apk add --no-cache git openssh \
    && mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

COPY local/php_conf.ini /usr/local/etc/php/conf.d/999-custom.ini

WORKDIR /app
